# 1️⃣ Use Node.js base image
FROM node:20-alpine

# 2️⃣ Set working directory
WORKDIR /src

# 3️⃣ Copy package files and install deps
COPY package*.json ./
RUN npm install --production

# 4️⃣ Copy the rest of your backend code
COPY . .

# 5️⃣ Expose your backend port
EXPOSE 4000

# 6️⃣ Start your app# build step
RUN npm run build
CMD ["node", "dist/app.js"]
# CMD ["npm", "start"]